version: '3'

services:
    db_radius:
        image: mustache7/postgres_freeradius
        environment:
            - POSTGRES_USER=radius
            - POSTGRES_PASSWORD=#>_Julius83
        networks:
            app_net:
                ipv4_address: 10.42.0.2
        ports:
            - "4243:5432"
        volumes:
            - /Users/admin/Documents/Projects/Docker/db_radius:/var/lib/postgresql/data

    db_mnemosine:
        image: postgres
        environment:
            - POSTGRES_USER=mnemosine
            - POSTGRES_PASSWORD=@)->SHazaM#
        networks:
            app_net:
                ipv4_address: 10.42.0.3
        ports:
            - "4242:5432"
        volumes:
            - /Users/admin/Documents/Projects/Docker/db_mnemosine:/var/lib/postgresql/data

networks:
    app_net:
        driver: bridge
        ipam:
            config:
                - subnet: 10.42.0.1/29
